server:
    port: 41200
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://39.107.24.27:41201/eureka/
#            defaultZone: http://127.0.0.1:41201/eureka/
    
    instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      hostname: ${spring.cloud.client.ipAddress}
      #注册时使用ip而不是主机名
      prefer-ip-address: true
      #如果是swagger 文档，直接写http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
      status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/
      health-check-url: http://${spring.cloud.client.ipAddress}:${server.port}/
      
spring:
    http:
      multipart:
        enabled: true
        max-file-size: 50MB #(这里是限制的文件大小)
        max-request-size: 50MB #(这里是限制的文件大小
        
zuul:  
    host:  
        socket-timeout-millis: 60000  
        connect-timeout-millis: 60000 
        
hystrix:  
    command:  
        default:  
            execution:  
                isolation:  
                    thread:  
                        timeoutInMilliseconds: 60000  

ribbon:  
    ReadTimeout: 60000  
    ConnectTimeout: 60000 

#自动配置  --现在 采用默认配置
#Zuul会为Eureka中的每个服务都自动创建一个默认的路由规则，这些默认规则的path会使用serviceId配置的服务名作为请求前缀，如方式二


#手动配置：
#方式一 等价于方式二path与serviceId组合使用的配置方式
#zuul:
#  routes:
#    user-service: /user-service/**
#方式二
#zuul:
#  routes:
#    user-service:
#      path: /user-service/**
#      serviceId: user-service
# ribbon:
#     eureka:
#         enable: false
# zuul:
#   routes:
#     user-service:
#       path: /user-service/**
#       url: http://39.107.24.27:41204/
#     user-operation:
#       path: /user-operation/**
#       url: http://39.107.24.27:41207/  
#     upload-service:
#       path: /upload-service/**
#       url:  http://39.107.24.27:41205/  

