server:
    port: 8076
    
    
spring:
    #AOP
    aop:
      auto: true
      proxy-target-class: true
    # 如果是测试环境则dev_model=true 不做验证码校验
    dev_model: false
    #开启redis 缓存session的两种方法一个是session.store 另外一个是注解 @EnableRedisHttpSession
      
    datasource:
      readSize: 1
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      MASTER:
        url: jdbc:mysql://47.104.226.173:3306/cxgm
        username: root
        password: '*Cxgm@App2018*'
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'

      SLAVE:
        url: jdbc:mysql://47.104.226.173:3306/cxgm
        username: root
        password: '*Cxgm@App2018*'
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'


#指定log的配置文件，以及记录Spring Boot的log级别  
logging:
    config: classpath:logback.xml     
 
    