server:
    port: 41203
    permitAllUrl: /center/home/list,/center/search
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.10.56:41201/eureka/
    
    instance:
      lease-renewal-interval-in-seconds: 48
      lease-expiration-duration-in-seconds: 28
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      hostname: ${spring.cloud.client.ipAddress}
      #注册时使用ip而不是主机名
      prefer-ip-address: true
      #如果是swagger 文档，直接写http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
      status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/
      health-check-url: http://${spring.cloud.client.ipAddress}:${server.port}/
spring:
    zipkin:
        base-url: http://39.107.24.27:41202
    # 如果是测试环境则dev_model=true 不做验证码校验
    dev_model: true

    session:
      store-type: redis

    datasource:
      readSize: 1
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://39.107.15.181:43106/mc_user
        username: niwolink_com
        password: Neco.wosh666@8*$@
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'

      read:
        url: jdbc:mysql://39.107.15.181:43106/mc_user
        username: niwolink_com
        password: Neco.wosh666@8*$@
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 'x'

    redis:
        database: 0
        host: 39.107.15.181
        password: Neco.wosh77@0217*$%
        port: 43709
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
hystrix:  
    command:  
        default:  
            execution:  
                isolation:  
                    thread:  
                        timeoutInMilliseconds: 60000  

ribbon:  
    ReadTimeout: 60000  
    ConnectTimeout: 60000 

geetest:
  id: 36864497f68bb5494a400df8a201cba0
  key: 77c867a96bc3d14cc47054da4969b957
  newfailback: true
block: 
  account: 
    default: 
      password: 12345678